const assert = require("node:assert/strict");
const test = require("node:test");

const transcript = require("../src/utils/transcript.js");

const playerResponseWithCaptions = {
  captions: {
    playerCaptionsTracklistRenderer: {
      captionTracks: [
        {
          baseUrl: "https://www.youtube.com/api/timedtext?v=abc&lang=en",
          languageCode: "en",
          kind: "asr",
          name: {
            simpleText: "English (auto-generated)"
          }
        },
        {
          baseUrl: "https://www.youtube.com/api/timedtext?v=abc&lang=es",
          languageCode: "es",
          name: {
            runs: [
              {
                text: "Spanish"
              }
            ]
          }
        }
      ]
    }
  },
  videoDetails: {
    videoId: "dQw4w9WgXcQ"
  }
};

function createPlayerResponse(videoId, baseUrl, label) {
  return {
    captions: {
      playerCaptionsTracklistRenderer: {
        captionTracks: [
          {
            baseUrl,
            languageCode: "en",
            kind: "asr",
            name: {
              simpleText: label || "English (auto-generated)"
            }
          }
        ]
      }
    },
    videoDetails: {
      videoId
    }
  };
}

test("normalizes manual and auto-generated caption tracks", () => {
  const tracks = transcript.getCaptionTracksFromPlayerResponse(playerResponseWithCaptions);

  assert.deepEqual(tracks, [
    {
      baseUrl: "https://www.youtube.com/api/timedtext?v=abc&lang=en",
      languageCode: "en",
      label: "English (auto-generated)",
      kind: "auto",
      isAutoGenerated: true
    },
    {
      baseUrl: "https://www.youtube.com/api/timedtext?v=abc&lang=es",
      languageCode: "es",
      label: "Spanish",
      kind: "manual",
      isAutoGenerated: false
    }
  ]);
});

test("reports transcript available when caption tracks exist", () => {
  const result = transcript.createAvailabilityResultFromPlayerResponse(playerResponseWithCaptions);

  assert.equal(result.status, "available");
  assert.equal(result.message, "Transcript available");
  assert.equal(result.tracks.length, 2);
  assert.equal(result.languages.length, 2);
});

test("reports no transcript when player response has no caption tracks", () => {
  const result = transcript.createAvailabilityResultFromPlayerResponse({
    captions: {
      playerCaptionsTracklistRenderer: {}
    }
  });

  assert.deepEqual(result, {
    status: "unavailable",
    message: "No transcript available for this video",
    tracks: [],
    languages: []
  });
});

test("extracts ytInitialPlayerResponse JSON from YouTube HTML", () => {
  const html = `
    <html>
      <script>
        var ytInitialPlayerResponse = ${JSON.stringify(playerResponseWithCaptions)};
      </script>
    </html>
  `;
  const playerResponse = transcript.extractPlayerResponseFromHtml(html, "dQw4w9WgXcQ");

  assert.equal(playerResponse.videoDetails.videoId, "dQw4w9WgXcQ");
});

test("detects transcript availability from a document script", async () => {
  const html = `var ytInitialPlayerResponse = ${JSON.stringify(playerResponseWithCaptions)};`;
  const fakeDocument = {
    scripts: [
      {
        textContent: html
      }
    ]
  };
  const result = await transcript.detectTranscriptAvailability({
    videoId: "dQw4w9WgXcQ",
    document: fakeDocument
  });

  assert.equal(result.status, "available");
  assert.equal(result.message, "Transcript available");
});

test("caption discovery uses the live player response before stale script tags", async () => {
  const originalPlayerResponse = global.ytInitialPlayerResponse;
  const liveResponse = createPlayerResponse("dQw4w9WgXcQ", "https://www.youtube.com/api/timedtext?v=live&lang=en", "Live English");
  const scriptResponse = createPlayerResponse("dQw4w9WgXcQ", "https://www.youtube.com/api/timedtext?v=script&lang=en", "Script English");

  global.ytInitialPlayerResponse = liveResponse;

  try {
    const result = await transcript.detectTranscriptAvailability({
      videoId: "dQw4w9WgXcQ",
      document: {
        scripts: [
          {
            textContent: `var ytInitialPlayerResponse = ${JSON.stringify(scriptResponse)};`
          }
        ]
      },
      fetchFn: async () => {
        throw new Error("watch page fetch should not run");
      }
    });

    assert.equal(result.status, "available");
    assert.equal(result.source, "live-player-response");
    assert.equal(result.tracks[0].baseUrl, "https://www.youtube.com/api/timedtext?v=live&lang=en");
  } finally {
    global.ytInitialPlayerResponse = originalPlayerResponse;
  }
});

test("caption discovery uses script tags before fetching the watch page", async () => {
  const scriptResponse = createPlayerResponse("dQw4w9WgXcQ", "https://www.youtube.com/api/timedtext?v=script&lang=en", "Script English");

  const result = await transcript.detectTranscriptAvailability({
    videoId: "dQw4w9WgXcQ",
    document: {
      scripts: [
        {
          textContent: `var ytInitialPlayerResponse = ${JSON.stringify(scriptResponse)};`
        }
      ]
    },
    fetchFn: async () => {
      throw new Error("watch page fetch should not run");
    }
  });

  assert.equal(result.status, "available");
  assert.equal(result.source, "script-tags");
  assert.equal(result.tracks[0].baseUrl, "https://www.youtube.com/api/timedtext?v=script&lang=en");
});

test("uses the fetch fallback when document player data is missing", async () => {
  const html = `var ytInitialPlayerResponse = ${JSON.stringify(playerResponseWithCaptions)};`;
  const result = await transcript.detectTranscriptAvailability({
    videoId: "dQw4w9WgXcQ",
    document: {
      scripts: []
    },
    fetchFn: async () => ({
      ok: true,
      text: async () => html
    })
  });

  assert.equal(result.status, "available");
  assert.equal(result.message, "Transcript available");
  assert.equal(result.source, "watch-page-fetch");
});

test("timedtext transcript loading succeeds before native or Android fallbacks run", async () => {
  const calls = [];
  const result = await transcript.fetchTranscriptRowsWithFallbacks({
    videoId: "dQw4w9WgXcQ",
    track: {
      baseUrl: "https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en",
      languageCode: "en"
    },
    fetchFn: async (url) => {
      calls.push(url);

      return {
        ok: true,
        text: async () => '<transcript><text start="1" dur="2">Timedtext worked</text></transcript>'
      };
    },
    nativeTranscriptFetcher: async () => {
      throw new Error("native fallback should not run");
    },
    apiKey: "test-api-key"
  });

  assert.equal(result.ok, true);
  assert.equal(result.source, "timedtext");
  assert.equal(result.rows[0].text, "Timedtext worked");
  assert.equal(calls.length, 1);
});

test("Android player transcript fallback runs only after timedtext and native rows fail", async () => {
  const androidPlayerResponse = {
    captions: {
      playerCaptionsTracklistRenderer: {
        captionTracks: [
          {
            baseUrl: "https://www.youtube.com/api/timedtext?v=android&lang=en&fmt=srv3",
            languageCode: "en",
            kind: "asr",
            name: {
              runs: [
                {
                  text: "English (auto-generated)"
                }
              ]
            }
          }
        ]
      }
    },
    videoDetails: {
      videoId: "dQw4w9WgXcQ"
    }
  };
  const requestedUrls = [];
  var nativeFallbackRan = false;

  const result = await transcript.fetchTranscriptRowsWithFallbacks({
    videoId: "dQw4w9WgXcQ",
    track: {
      baseUrl: "https://www.youtube.com/api/timedtext?v=web&lang=en",
      languageCode: "en"
    },
    apiKey: "test-api-key",
    fetchFn: async (url, options) => {
      requestedUrls.push(url);

      if (options && options.method === "POST") {
        return {
          ok: true,
          json: async () => androidPlayerResponse
        };
      }

      return {
        ok: true,
        text: async () => url.indexOf("v=android") !== -1
          ? '<transcript><text start="1" dur="2">Android worked</text></transcript>'
          : "<transcript></transcript>"
      };
    },
    nativeTranscriptFetcher: async () => {
      nativeFallbackRan = true;
      return [];
    }
  });

  assert.equal(nativeFallbackRan, true);
  assert.equal(result.ok, true);
  assert.equal(result.source, "android-player");
  assert.equal(result.rows[0].text, "Android worked");
  assert.ok(requestedUrls.some((url) => /\/youtubei\/v1\/player\?key=test-api-key$/.test(url)));
});

test("falls back to web caption URLs when Android player fallback fails", async () => {
  const fakeDocument = {
    scripts: [
      {
        textContent: [
          'ytcfg.set({"INNERTUBE_API_KEY":"test-api-key"});',
          `var ytInitialPlayerResponse = ${JSON.stringify(playerResponseWithCaptions)};`
        ].join("\n")
      }
    ]
  };

  const result = await transcript.detectTranscriptAvailability({
    videoId: "dQw4w9WgXcQ",
    document: fakeDocument,
    fetchFn: async () => {
      throw new Error("Network failed");
    }
  });

  assert.equal(result.status, "available");
  assert.equal(result.tracks[0].baseUrl, "https://www.youtube.com/api/timedtext?v=abc&lang=en");
});

test("reports detection failed when player data cannot be found", async () => {
  const result = await transcript.detectTranscriptAvailability({
    videoId: "dQw4w9WgXcQ",
    document: {
      scripts: []
    },
    fetchFn: async () => ({
      ok: true,
      text: async () => "<html></html>"
    })
  });

  assert.deepEqual(result, {
    status: "failed",
    message: "Transcript detection failed",
    tracks: [],
    languages: []
  });
});

test("parses XML transcript text into timestamped rows", () => {
  const xml = '<transcript><text start="0.17" dur="2.5">Hello &amp; welcome</text><text start="12.04" dur="3">next line</text></transcript>';
  const rows = transcript.parseTranscriptResponse(xml);

  assert.deepEqual(rows, [
    {
      startSeconds: 0.17,
      durationSeconds: 2.5,
      timestamp: "0:00",
      text: "Hello & welcome"
    },
    {
      startSeconds: 12.04,
      durationSeconds: 3,
      timestamp: "0:12",
      text: "next line"
    }
  ]);
});

test("falls back when browser Trusted Types blocks innerHTML entity decoding", () => {
  const originalDocument = global.document;

  global.document = {
    createElement: () => {
      const element = {};

      Object.defineProperty(element, "innerHTML", {
        set: () => {
          throw new TypeError("This document requires TrustedHTML assignment.");
        }
      });

      return element;
    }
  };

  try {
    const rows = transcript.parseTranscriptResponse('<transcript><text start="1" dur="2">Safe &amp; readable</text></transcript>');

    assert.equal(rows[0].text, "Safe & readable");
  } finally {
    global.document = originalDocument;
  }
});

test("parses JSON3 transcript events into timestamped rows", () => {
  const json = JSON.stringify({
    events: [
      {
        tStartMs: 17000,
        dDurationMs: 2400,
        segs: [
          { utf8: "Hello " },
          { utf8: "again" }
        ]
      },
      {
        tStartMs: 724000,
        segs: [
          { utf8: "long video" }
        ]
      }
    ]
  });
  const rows = transcript.parseTranscriptResponse(json);

  assert.equal(rows[0].timestamp, "0:17");
  assert.equal(rows[0].text, "Hello again");
  assert.equal(rows[1].timestamp, "12:04");
  assert.equal(rows[1].text, "long video");
});

test("parses SRV3 timedtext XML into timestamped rows", () => {
  const xml = [
    "<timedtext>",
    "<body>",
    '<p t="17000" d="2400"><s>Hello </s><s>again</s></p>',
    '<p t="724000"><s>long video</s></p>',
    "</body>",
    "</timedtext>"
  ].join("");
  const rows = transcript.parseTranscriptResponse(xml);

  assert.equal(rows[0].timestamp, "0:17");
  assert.equal(rows[0].durationSeconds, 2.4);
  assert.equal(rows[0].text, "Hello again");
  assert.equal(rows[1].timestamp, "12:04");
  assert.equal(rows[1].text, "long video");
});

test("skips empty transcript segments", () => {
  const xml = '<transcript><text start="0" dur="1">   </text><text start="1" dur="1">Real text</text></transcript>';
  const rows = transcript.parseTranscriptResponse(xml);

  assert.equal(rows.length, 1);
  assert.equal(rows[0].text, "Real text");
});

test("parses YouTube native transcript panel rows", () => {
  function createFakeElement(textContent, childrenBySelector) {
    return {
      textContent,
      querySelector: (selector) => childrenBySelector[selector] || null
    };
  }

  const segments = [
    createFakeElement("", {
      ".ytwTranscriptSegmentViewModelTimestamp": createFakeElement("0:05", {}),
      "span[role=\"text\"]": createFakeElement("First native row", {})
    }),
    createFakeElement("", {
      ".ytwTranscriptSegmentViewModelTimestamp": createFakeElement("1:25", {}),
      "span[role=\"text\"]": createFakeElement("Second native row", {})
    })
  ];
  const fakeDocument = {
    querySelectorAll: (selector) => selector === "transcript-segment-view-model" ? segments : []
  };

  assert.deepEqual(transcript.parseNativeTranscriptRowsFromDocument(fakeDocument), [
    {
      startSeconds: 5,
      durationSeconds: 0,
      timestamp: "0:05",
      text: "First native row"
    },
    {
      startSeconds: 85,
      durationSeconds: 0,
      timestamp: "1:25",
      text: "Second native row"
    }
  ]);
});

test("builds caption fetch URLs with original, JSON3, SRV3, and XML fallbacks", () => {
  const urls = transcript.buildCaptionFetchUrls("https://www.youtube.com/api/timedtext?v=abc&lang=en&fmt=vtt");

  assert.deepEqual(urls, [
    "https://www.youtube.com/api/timedtext?v=abc&lang=en&fmt=vtt",
    "https://www.youtube.com/api/timedtext?v=abc&lang=en&fmt=json3",
    "https://www.youtube.com/api/timedtext?v=abc&lang=en&fmt=srv3",
    "https://www.youtube.com/api/timedtext?v=abc&lang=en"
  ]);
});

test("fetches and parses a caption track", async () => {
  const rows = await transcript.fetchTranscriptTrack(
    {
      baseUrl: "https://www.youtube.com/api/timedtext?v=abc&lang=en"
    },
    async (url) => ({
      ok: true,
      requestedUrl: url,
      text: async () => '<transcript><text start="17" dur="2">Fetched text</text></transcript>'
    })
  );

  assert.deepEqual(rows, [
    {
      startSeconds: 17,
      durationSeconds: 2,
      timestamp: "0:17",
      text: "Fetched text"
    }
  ]);
});

test("tries fallback caption formats before failing", async () => {
  const requestedUrls = [];
  const rows = await transcript.fetchTranscriptTrack(
    {
      baseUrl: "https://www.youtube.com/api/timedtext?v=abc&lang=en&fmt=vtt"
    },
    async (url) => {
      requestedUrls.push(url);

      if (url.includes("fmt=json3")) {
        return {
          ok: true,
          text: async () => JSON.stringify({
            events: [
              {
                tStartMs: 17000,
                dDurationMs: 2000,
                segs: [
                  { utf8: "Fallback worked" }
                ]
              }
            ]
          })
        };
      }

      return {
        ok: true,
        text: async () => "<transcript></transcript>"
      };
    }
  );

  assert.deepEqual(requestedUrls, [
    "https://www.youtube.com/api/timedtext?v=abc&lang=en&fmt=vtt",
    "https://www.youtube.com/api/timedtext?v=abc&lang=en&fmt=json3"
  ]);
  assert.equal(rows[0].text, "Fallback worked");
});

test("logs sanitized caption fetch attempts when a debug logger is provided", async () => {
  const messages = [];

  await transcript.fetchTranscriptTrack(
    {
      baseUrl: "https://www.youtube.com/api/timedtext?v=abc&lang=en&fmt=json3&signature=secret&expire=123"
    },
    async () => ({
      ok: true,
      text: async () => JSON.stringify({
        events: [
          {
            tStartMs: 1000,
            segs: [
              { utf8: "Logged safely" }
            ]
          }
        ]
      })
    }),
    {
      debugLogger: (message) => messages.push(message)
    }
  );

  const combinedMessages = messages.join("\n");

  assert.ok(messages.length > 1);
  assert.match(combinedMessages, /signature=REDACTED/);
  assert.match(combinedMessages, /expire=REDACTED/);
  assert.doesNotMatch(combinedMessages, /secret/);
});

test("throws a clear error when a fetched caption track has no readable rows", async () => {
  await assert.rejects(
    () => transcript.fetchTranscriptTrack(
      {
        baseUrl: "https://www.youtube.com/api/timedtext?v=abc&lang=en"
      },
      async () => ({
        ok: true,
        text: async () => "<transcript></transcript>"
      })
    ),
    /No readable transcript rows/
  );
});
