(function attachTranscriptHelpers(root) {
  "use strict";

  var STATUS_MESSAGES = {
    checking: "Checking transcript availability...",
    available: "Transcript available",
    unavailable: "No transcript available for this video",
    failed: "Transcript detection failed"
  };
  var ANDROID_INNERTUBE_CONTEXT = {
    client: {
      clientName: "ANDROID",
      clientVersion: "20.10.38"
    }
  };

  function getTextFromYouTubeText(value) {
    if (!value) {
      return "";
    }

    if (value.simpleText) {
      return value.simpleText;
    }

    if (Array.isArray(value.runs)) {
      return value.runs.map(function mapRun(run) {
        return run && run.text ? run.text : "";
      }).join("");
    }

    return "";
  }

  function normalizeCaptionTrack(track) {
    if (!track || !track.baseUrl) {
      return null;
    }

    var isAutoGenerated = track.kind === "asr";
    var languageCode = track.languageCode || "unknown";
    var label = getTextFromYouTubeText(track.name) || languageCode;
    var normalizedTrack = {
      baseUrl: track.baseUrl,
      languageCode: languageCode,
      label: label,
      kind: isAutoGenerated ? "auto" : "manual",
      isAutoGenerated: isAutoGenerated
    };

    if (track.isTranslatable === true) {
      normalizedTrack.isTranslatable = true;
    }

    return normalizedTrack;
  }

  function createTranslatedTrack(sourceTrack, translationLanguage) {
    var languageCode = translationLanguage && translationLanguage.languageCode;
    var label = getTextFromYouTubeText(translationLanguage && translationLanguage.languageName) || languageCode;

    return {
      baseUrl: sourceTrack.baseUrl,
      languageCode: languageCode,
      label: label + " (translated)",
      kind: "translated",
      isAutoGenerated: false,
      isTranslated: true,
      sourceLanguageCode: sourceTrack.languageCode,
      translationLanguageCode: languageCode
    };
  }

  function hasDirectCaptionForLanguage(tracks, languageCode) {
    return tracks.some(function findDirectTrack(track) {
      return !track.isTranslated && track.languageCode === languageCode;
    });
  }

  function addTranslatedTracksIfAvailable(tracks, translationLanguages) {
    var safeTracks = Array.isArray(tracks) ? tracks.slice() : [];
    var translatableSourceTrack;

    if (!Array.isArray(translationLanguages)) {
      return safeTracks;
    }

    translatableSourceTrack = safeTracks.find(function findTranslatableTrack(track) {
      return track.isTranslatable === true;
    });

    if (!translatableSourceTrack) {
      return safeTracks;
    }

    translationLanguages.forEach(function addTranslatedTrack(translationLanguage) {
      var languageCode = translationLanguage && translationLanguage.languageCode;

      if (!languageCode || languageCode === translatableSourceTrack.languageCode || hasDirectCaptionForLanguage(safeTracks, languageCode)) {
        return;
      }

      safeTracks.push(createTranslatedTrack(translatableSourceTrack, translationLanguage));
    });

    return safeTracks;
  }

  function getCaptionTracksFromPlayerResponse(playerResponse) {
    // Fragile YouTube-internal logic: caption tracks currently live at this
    // nested path inside ytInitialPlayerResponse. YouTube can change it.
    var captions = playerResponse && playerResponse.captions;
    var renderer = captions && captions.playerCaptionsTracklistRenderer;
    var captionTracks = renderer && renderer.captionTracks;

    if (!Array.isArray(captionTracks)) {
      return [];
    }

    return addTranslatedTracksIfAvailable(
      captionTracks.map(normalizeCaptionTrack).filter(Boolean),
      renderer.translationLanguages
    );
  }

  function getLanguagesFromTracks(tracks) {
    var seen = {};
    var languages = [];

    tracks.forEach(function addLanguage(track) {
      var key = track.languageCode + "|" + track.label + "|" + track.kind;

      if (seen[key]) {
        return;
      }

      seen[key] = true;
      languages.push({
        languageCode: track.languageCode,
        label: track.label,
        kind: track.kind,
        isAutoGenerated: track.isAutoGenerated
      });
    });

    return languages;
  }

  function createCheckingAvailabilityResult() {
    return {
      status: "checking",
      message: STATUS_MESSAGES.checking,
      tracks: [],
      languages: []
    };
  }

  function createFailedAvailabilityResult() {
    return {
      status: "failed",
      message: STATUS_MESSAGES.failed,
      tracks: [],
      languages: []
    };
  }

  function createUnavailableAvailabilityResult() {
    return {
      status: "unavailable",
      message: STATUS_MESSAGES.unavailable,
      tracks: [],
      languages: []
    };
  }

  function createAvailabilityResultFromPlayerResponse(playerResponse) {
    var tracks = getCaptionTracksFromPlayerResponse(playerResponse);

    if (tracks.length === 0) {
      return createUnavailableAvailabilityResult();
    }

    return {
      status: "available",
      message: STATUS_MESSAGES.available,
      tracks: tracks,
      languages: getLanguagesFromTracks(tracks)
    };
  }

  function createAvailabilityResultFromTrackSource(trackSource) {
    var safeSource = trackSource || {};
    var tracks = Array.isArray(safeSource.tracks) ? safeSource.tracks : [];

    if (tracks.length === 0) {
      return createUnavailableAvailabilityResult();
    }

    return {
      status: "available",
      message: STATUS_MESSAGES.available,
      tracks: tracks,
      languages: getLanguagesFromTracks(tracks),
      source: safeSource.source || "unknown",
      videoId: safeSource.videoId || null,
      apiKey: safeSource.apiKey || null
    };
  }

  function createTrackSourceResult(source, playerResponse, videoId, apiKey) {
    var tracks = getCaptionTracksFromPlayerResponse(playerResponse);

    if (!playerResponse) {
      return {
        ok: false,
        reason: "Player response not found",
        source: source,
        foundPlayerResponse: false
      };
    }

    if (tracks.length === 0) {
      return {
        ok: false,
        reason: "No caption tracks found",
        source: source,
        foundPlayerResponse: true
      };
    }

    return {
      ok: true,
      videoId: videoId,
      tracks: tracks,
      source: source,
      apiKey: apiKey || null
    };
  }

  function extractJsonObjectAt(text, startIndex) {
    var objectStart = text.indexOf("{", startIndex);
    var depth = 0;
    var inString = false;
    var stringQuote = "";
    var escaped = false;
    var index;
    var character;

    if (objectStart === -1) {
      return null;
    }

    for (index = objectStart; index < text.length; index += 1) {
      character = text[index];

      if (inString) {
        if (escaped) {
          escaped = false;
        } else if (character === "\\") {
          escaped = true;
        } else if (character === stringQuote) {
          inString = false;
          stringQuote = "";
        }

        continue;
      }

      if (character === "\"" || character === "'") {
        inString = true;
        stringQuote = character;
        continue;
      }

      if (character === "{") {
        depth += 1;
      } else if (character === "}") {
        depth -= 1;

        if (depth === 0) {
          return text.slice(objectStart, index + 1);
        }
      }
    }

    return null;
  }

  function extractPlayerResponseFromHtml(html, videoId) {
    var marker = "ytInitialPlayerResponse";
    var searchStart = 0;
    var markerIndex;
    var equalsIndex;
    var jsonText;
    var playerResponse;

    if (!html) {
      return null;
    }

    // Fragile YouTube-internal logic: YouTube embeds this JSON in page scripts.
    // If that variable name or shape changes, detection should fail cleanly.
    while ((markerIndex = html.indexOf(marker, searchStart)) !== -1) {
      equalsIndex = html.indexOf("=", markerIndex);

      if (equalsIndex === -1) {
        return null;
      }

      jsonText = extractJsonObjectAt(html, equalsIndex);

      if (jsonText) {
        try {
          playerResponse = JSON.parse(jsonText);

          if (!videoId || (playerResponse.videoDetails && playerResponse.videoDetails.videoId === videoId)) {
            return playerResponse;
          }
        } catch (error) {
          return null;
        }
      }

      searchStart = markerIndex + marker.length;
    }

    return null;
  }

  function findPlayerResponseFromGlobal(videoId) {
    // YouTube updates this global variable during SPA navigation, even when
    // the <script> tags in the DOM still contain the previous video's data.
    var globalResponse = root.ytInitialPlayerResponse;

    if (!globalResponse || typeof globalResponse !== "object") {
      return null;
    }

    if (videoId && globalResponse.videoDetails && globalResponse.videoDetails.videoId !== videoId) {
      return null;
    }

    return globalResponse;
  }

  function getCaptionTracksFromLivePlayerResponse(videoId) {
    var playerResponse = findPlayerResponseFromGlobal(videoId);

    return createTrackSourceResult("live-player-response", playerResponse, videoId, null);
  }

  function findPlayerResponseInDocument(documentValue, videoId) {
    var scripts = documentValue && documentValue.scripts;
    var index;
    var scriptText;
    var playerResponse;

    if (!scripts) {
      return null;
    }

    for (index = 0; index < scripts.length; index += 1) {
      scriptText = scripts[index] && scripts[index].textContent;
      playerResponse = extractPlayerResponseFromHtml(scriptText, videoId);

      if (playerResponse) {
        return playerResponse;
      }
    }

    return null;
  }

  function getCaptionTracksFromScriptTags(videoId, documentValue) {
    var playerResponse = findPlayerResponseInDocument(documentValue, videoId);
    var apiKey = findInnertubeApiKeyInDocument(documentValue);

    return createTrackSourceResult("script-tags", playerResponse, videoId, apiKey);
  }

  function extractInnertubeApiKeyFromHtml(html) {
    var match = String(html || "").match(/"INNERTUBE_API_KEY"\s*:\s*"([a-zA-Z0-9_-]+)"/);

    return match ? match[1] : null;
  }

  function findInnertubeApiKeyInDocument(documentValue) {
    var scripts = documentValue && documentValue.scripts;
    var index;
    var apiKey;

    if (!scripts) {
      return null;
    }

    for (index = 0; index < scripts.length; index += 1) {
      apiKey = extractInnertubeApiKeyFromHtml(scripts[index] && scripts[index].textContent);

      if (apiKey) {
        return apiKey;
      }
    }

    return null;
  }

  async function fetchWatchPageHtml(videoId, fetchFn) {
    var requestUrl;
    var response;

    if (!videoId || typeof fetchFn !== "function") {
      return null;
    }

    requestUrl = "https://www.youtube.com/watch?v=" + encodeURIComponent(videoId);
    response = await fetchFn(requestUrl, {
      credentials: "include"
    });

    if (!response || !response.ok || typeof response.text !== "function") {
      return null;
    }

    return response.text();
  }

  async function fetchPlayerResponseFromWatchPage(videoId, fetchFn) {
    var html = await fetchWatchPageHtml(videoId, fetchFn);

    return extractPlayerResponseFromHtml(html, videoId);
  }

  async function getCaptionTracksFromWatchPageFetch(videoId, fetchFn) {
    var html = await fetchWatchPageHtml(videoId, fetchFn);
    var playerResponse = extractPlayerResponseFromHtml(html, videoId);
    var apiKey = extractInnertubeApiKeyFromHtml(html);

    return createTrackSourceResult("watch-page-fetch", playerResponse, videoId, apiKey);
  }

  async function fetchAndroidPlayerResponse(videoId, apiKey, fetchFn) {
    var requestUrl;
    var response;
    var playerResponse;
    var responseText;

    if (!videoId || !apiKey || typeof fetchFn !== "function") {
      return null;
    }

    try {
      requestUrl = "https://www.youtube.com/youtubei/v1/player?key=" + encodeURIComponent(apiKey);
      response = await fetchFn(requestUrl, {
        method: "POST",
        credentials: "include",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          context: ANDROID_INNERTUBE_CONTEXT,
          videoId: videoId
        })
      });

      if (!response || !response.ok) {
        return null;
      }

      if (typeof response.json === "function") {
        playerResponse = await response.json();
      } else if (typeof response.text === "function") {
        responseText = await response.text();
        playerResponse = JSON.parse(responseText);
      } else {
        return null;
      }

      if (videoId && playerResponse.videoDetails && playerResponse.videoDetails.videoId !== videoId) {
        return null;
      }

      return playerResponse;
    } catch (error) {
      return null;
    }
  }

  function normalizeWhitespace(value) {
    return String(value || "").replace(/\s+/g, " ").trim();
  }

  function formatTimestamp(totalSeconds) {
    var safeSeconds = Math.max(0, Math.floor(Number(totalSeconds) || 0));
    var hours = Math.floor(safeSeconds / 3600);
    var minutes = Math.floor((safeSeconds % 3600) / 60);
    var seconds = safeSeconds % 60;
    var minuteText = String(minutes).padStart(hours > 0 ? 2 : 1, "0");
    var secondText = String(seconds).padStart(2, "0");

    if (hours > 0) {
      return hours + ":" + minuteText + ":" + secondText;
    }

    return minuteText + ":" + secondText;
  }

  function parseTimestampTextToSeconds(timestampText) {
    var parts = String(timestampText || "").trim().split(":");
    var totalSeconds = 0;
    var index;
    var numberValue;

    if (parts.length < 2 || parts.length > 3) {
      return NaN;
    }

    for (index = 0; index < parts.length; index += 1) {
      numberValue = Number(parts[index]);

      if (Number.isNaN(numberValue)) {
        return NaN;
      }

      totalSeconds = (totalSeconds * 60) + numberValue;
    }

    return totalSeconds;
  }

  function decodeHtmlEntities(value) {
    var text = String(value || "");
    var entityMap = {
      amp: "&",
      lt: "<",
      gt: ">",
      quot: "\"",
      apos: "'",
      nbsp: " "
    };

    if (root.document && typeof root.document.createElement === "function") {
      try {
        var textarea = root.document.createElement("textarea");
        textarea.innerHTML = text;
        return textarea.value;
      } catch (error) {
        // YouTube can enforce Trusted Types, which blocks assigning strings to
        // innerHTML. The regex decoder below handles the entities we need.
      }
    }

    return text.replace(/&(#x?[0-9a-fA-F]+|[a-zA-Z]+);/g, function replaceEntity(match, entity) {
      var codePoint;

      if (entity[0] === "#") {
        if (entity[1] && entity[1].toLowerCase() === "x") {
          codePoint = parseInt(entity.slice(2), 16);
        } else {
          codePoint = parseInt(entity.slice(1), 10);
        }

        if (!Number.isNaN(codePoint)) {
          return String.fromCodePoint(codePoint);
        }
      }

      return Object.prototype.hasOwnProperty.call(entityMap, entity) ? entityMap[entity] : match;
    });
  }

  function parseXmlAttributes(attributeText) {
    var attributes = {};
    var attributePattern = /([a-zA-Z_:.-]+)="([^"]*)"/g;
    var match;

    while ((match = attributePattern.exec(attributeText || "")) !== null) {
      attributes[match[1]] = decodeHtmlEntities(match[2]);
    }

    return attributes;
  }

  function createTranscriptRow(startSeconds, durationSeconds, text) {
    var cleanText = normalizeWhitespace(decodeHtmlEntities(String(text || "").replace(/<[^>]*>/g, "")));
    var safeStart = Number(startSeconds);
    var safeDuration = Number(durationSeconds);

    if (!cleanText || Number.isNaN(safeStart)) {
      return null;
    }

    return {
      startSeconds: safeStart,
      durationSeconds: Number.isNaN(safeDuration) ? 0 : safeDuration,
      timestamp: formatTimestamp(safeStart),
      text: cleanText
    };
  }

  function createTranscriptRowFromMilliseconds(startMs, durationMs, text) {
    return createTranscriptRow(
      Number(startMs || 0) / 1000,
      Number(durationMs || 0) / 1000,
      text
    );
  }

  function parseXmlTranscript(responseText) {
    var rows = [];
    var textPattern = /<text\b([^>]*)>([\s\S]*?)<\/text>/g;
    var match;
    var attributes;
    var row;

    while ((match = textPattern.exec(responseText || "")) !== null) {
      attributes = parseXmlAttributes(match[1]);
      row = createTranscriptRow(attributes.start, attributes.dur, match[2]);

      if (row) {
        rows.push(row);
      }
    }

    return rows;
  }

  function parseSrv3Transcript(responseText) {
    var rows = [];
    var paragraphPattern = /<p\b([^>]*)>([\s\S]*?)<\/p>/g;
    var match;
    var attributes;
    var row;

    while ((match = paragraphPattern.exec(responseText || "")) !== null) {
      attributes = parseXmlAttributes(match[1]);
      row = createTranscriptRowFromMilliseconds(attributes.t, attributes.d, match[2]);

      if (row) {
        rows.push(row);
      }
    }

    return rows;
  }

  function countXmlTextNodes(responseText) {
    var match = String(responseText || "").match(/<text\b/g);

    return match ? match.length : 0;
  }

  function countSrv3ParagraphNodes(responseText) {
    var match = String(responseText || "").match(/<p\b/g);

    return match ? match.length : 0;
  }

  function parseJsonTranscript(responseText) {
    var parsed = JSON.parse(responseText);
    var events = Array.isArray(parsed.events) ? parsed.events : [];
    var rows = [];

    events.forEach(function addEvent(event) {
      var segments = Array.isArray(event.segs) ? event.segs : [];
      var text = segments.map(function mapSegment(segment) {
        return segment && segment.utf8 ? segment.utf8 : "";
      }).join("");
      var row = createTranscriptRow(
        Number(event.tStartMs || 0) / 1000,
        Number(event.dDurationMs || 0) / 1000,
        text
      );

      if (row) {
        rows.push(row);
      }
    });

    return rows;
  }

  function getErrorMessage(error) {
    return error && error.message ? error.message : String(error || "Unknown error");
  }

  function createParserResult(name, rows, reason) {
    return {
      name: name,
      rows: rows || [],
      reason: reason || ""
    };
  }

  function parseTranscriptResponseWithDebug(responseText) {
    var text = String(responseText || "").trim();
    var attempts = [];
    var rows;
    var jsonFirstCharacter;
    var jsonNodeCount;
    var xmlNodeCount;
    var srv3NodeCount;

    if (!text) {
      attempts.push(createParserResult("json3", [], "response text is empty"));
      attempts.push(createParserResult("xml", [], "response text is empty"));
      attempts.push(createParserResult("srv3", [], "response text is empty"));

      return {
        rows: [],
        parser: "",
        attempts: attempts
      };
    }

    jsonFirstCharacter = text[0];

    try {
      if (jsonFirstCharacter !== "{" && jsonFirstCharacter !== "[") {
        attempts.push(createParserResult("json3", [], "response does not start with JSON"));
      } else {
        rows = parseJsonTranscript(text);
        attempts.push(createParserResult(
          "json3",
          rows,
          rows.length > 0 ? "" : "JSON3 parsed but produced 0 readable rows"
        ));

        if (rows.length > 0) {
          return {
            rows: rows,
            parser: "json3",
            attempts: attempts
          };
        }
      }
    } catch (error) {
      attempts.push(createParserResult("json3", [], "JSON3 parser failed: " + getErrorMessage(error)));
    }

    try {
      xmlNodeCount = countXmlTextNodes(text);
      rows = parseXmlTranscript(text);
      attempts.push(createParserResult(
        "xml",
        rows,
        rows.length > 0 ? "" : "XML parser found " + xmlNodeCount + " <text> nodes and produced 0 readable rows"
      ));

      if (rows.length > 0) {
        return {
          rows: rows,
          parser: "xml",
          attempts: attempts
        };
      }
    } catch (error) {
      attempts.push(createParserResult("xml", [], "XML parser failed: " + getErrorMessage(error)));
    }

    try {
      srv3NodeCount = countSrv3ParagraphNodes(text);
      rows = parseSrv3Transcript(text);
      attempts.push(createParserResult(
        "srv3",
        rows,
        rows.length > 0 ? "" : "SRV3 parser found " + srv3NodeCount + " <p> nodes and produced 0 readable rows"
      ));

      if (rows.length > 0) {
        return {
          rows: rows,
          parser: "srv3",
          attempts: attempts
        };
      }
    } catch (error) {
      attempts.push(createParserResult("srv3", [], "SRV3 parser failed: " + getErrorMessage(error)));
    }

    jsonNodeCount = Array.isArray(attempts) ? attempts.length : 0;

    return {
      rows: [],
      parser: "",
      attempts: attempts.slice(0, jsonNodeCount)
    };
  }

  function parseTranscriptResponse(responseText) {
    return parseTranscriptResponseWithDebug(responseText).rows;
  }

  function parseNativeTranscriptRowsFromDocument(documentValue) {
    var rows = [];
    var segments;

    if (!documentValue || typeof documentValue.querySelectorAll !== "function") {
      return rows;
    }

    segments = Array.prototype.slice.call(documentValue.querySelectorAll("transcript-segment-view-model"));

    segments.forEach(function parseSegment(segment) {
      var timestampElement = segment && typeof segment.querySelector === "function"
        ? segment.querySelector(".ytwTranscriptSegmentViewModelTimestamp")
        : null;
      var textElement = segment && typeof segment.querySelector === "function"
        ? segment.querySelector("span[role=\"text\"]")
        : null;
      var startSeconds = parseTimestampTextToSeconds(timestampElement ? timestampElement.textContent : "");
      var row = createTranscriptRow(startSeconds, 0, textElement ? textElement.textContent : "");

      if (row) {
        rows.push(row);
      }
    });

    return rows;
  }

  function addUniqueUrl(urls, seen, url) {
    if (!url || seen[url]) {
      return;
    }

    seen[url] = true;
    urls.push(url);
  }

  function buildUrlWithCaptionFormat(baseUrl, format, translationLanguageCode) {
    var url;

    try {
      url = new URL(baseUrl);

      if (typeof format === "string") {
        if (format) {
          url.searchParams.set("fmt", format);
        } else {
          url.searchParams.delete("fmt");
        }
      }

      if (translationLanguageCode) {
        url.searchParams.set("tlang", translationLanguageCode);
      }

      return url.toString();
    } catch (error) {
      return null;
    }
  }

  function buildCaptionFetchUrls(baseUrl, translationLanguageCode) {
    var urls = [];
    var seen = {};

    addUniqueUrl(urls, seen, buildUrlWithCaptionFormat(baseUrl, undefined, translationLanguageCode) || baseUrl);
    addUniqueUrl(urls, seen, buildUrlWithCaptionFormat(baseUrl, "json3", translationLanguageCode));
    addUniqueUrl(urls, seen, buildUrlWithCaptionFormat(baseUrl, "srv3", translationLanguageCode));
    addUniqueUrl(urls, seen, buildUrlWithCaptionFormat(baseUrl, "", translationLanguageCode));

    return urls;
  }

  function sanitizeCaptionUrlForLog(urlText) {
    var hiddenParams = {
      expire: true,
      key: true,
      lsig: true,
      sig: true,
      signature: true,
      token: true
    };
    var url;

    try {
      url = new URL(urlText);
      url.searchParams.forEach(function redactParam(value, key) {
        if (hiddenParams[String(key).toLowerCase()]) {
          url.searchParams.set(key, "REDACTED");
        }
      });

      return url.toString();
    } catch (error) {
      return "[unreadable caption URL]";
    }
  }

  function logCaptionFetchAttempt(options, url) {
    var logger = options && options.debugLogger;

    if (typeof logger !== "function") {
      return;
    }

    try {
      logger("Trying caption URL: " + sanitizeCaptionUrlForLog(url));
    } catch (error) {
      // Development logging should never break transcript loading.
    }
  }

  function logCaptionDebug(options, message) {
    var logger = options && options.debugLogger;

    if (typeof logger !== "function") {
      return;
    }

    try {
      logger(message);
    } catch (error) {
      // Development logging should never break transcript loading.
    }
  }

  function getHeaderValue(response, headerName) {
    if (!response || !response.headers || typeof response.headers.get !== "function") {
      return "unknown";
    }

    return response.headers.get(headerName) || "missing";
  }

  function getResponsePreview(responseText) {
    return String(responseText || "").slice(0, 300).replace(/\s+/g, " ").trim();
  }

  function logParserAttempts(options, parseResult) {
    var attempts = parseResult && Array.isArray(parseResult.attempts) ? parseResult.attempts : [];

    attempts.forEach(function logAttempt(attempt) {
      if (attempt.rows.length > 0) {
        logCaptionDebug(options, "Parser " + attempt.name + " succeeded with " + attempt.rows.length + " rows");
        return;
      }

      logCaptionDebug(options, "Parser " + attempt.name + " failed: " + attempt.reason);
    });
  }

  async function fetchTranscriptTrack(track, fetchFn, options) {
    var urls;
    var index;
    var url;
    var response;
    var responseText;
    var rows;
    var foundReadableResponse = false;
    var parseResult;

    if (!track || !track.baseUrl || typeof fetchFn !== "function") {
      throw new Error("Transcript track is missing");
    }

    urls = buildCaptionFetchUrls(track.baseUrl, track.isTranslated ? track.translationLanguageCode : null);

    for (index = 0; index < urls.length; index += 1) {
      url = urls[index];
      logCaptionFetchAttempt(options, url);

      try {
        response = await fetchFn(url, {
          credentials: "include"
        });

        if (!response) {
          logCaptionDebug(options, "HTTP status: no response object");
          continue;
        }

        logCaptionDebug(options, "HTTP status: " + (response.status || "unknown"));
        logCaptionDebug(options, "Content-Type: " + getHeaderValue(response, "content-type"));

        if (!response || !response.ok || typeof response.text !== "function") {
          continue;
        }

        responseText = await response.text();
        logCaptionDebug(options, "Response first 300 chars: " + (getResponsePreview(responseText) || "[empty response]"));

        parseResult = parseTranscriptResponseWithDebug(responseText);
        logParserAttempts(options, parseResult);
        rows = parseResult.rows;

        if (rows.length > 0) {
          return rows;
        }

        foundReadableResponse = true;
      } catch (error) {
        logCaptionDebug(options, "Caption fetch attempt failed: " + getErrorMessage(error));
        // Try the next caption format before showing a final failure.
      }
    }

    if (foundReadableResponse) {
      throw new Error("No readable transcript rows");
    }

    throw new Error("Transcript fetch failed");
  }

  async function fetchTimedTextTranscript(track, fetchFn, options) {
    try {
      return {
        ok: true,
        rows: await fetchTranscriptTrack(track, fetchFn, options),
        source: "timedtext"
      };
    } catch (error) {
      return {
        ok: false,
        reason: getErrorMessage(error),
        source: "timedtext"
      };
    }
  }

  function findBestAndroidCaptionTrack(tracks, originalTrack) {
    var safeTracks = Array.isArray(tracks) ? tracks : [];
    var languageCode = originalTrack && (originalTrack.isTranslated ? originalTrack.sourceLanguageCode : originalTrack.languageCode);
    var kind = originalTrack && originalTrack.kind;

    return safeTracks.find(function findExactTrack(track) {
      return track.languageCode === languageCode && track.kind === kind;
    }) || safeTracks.find(function findLanguageTrack(track) {
      return track.languageCode === languageCode;
    }) || safeTracks[0] || null;
  }

  async function fetchAndroidPlayerTranscript(videoId, track, apiKey, fetchFn, options) {
    var playerResponse = await fetchAndroidPlayerResponse(videoId, apiKey, fetchFn);
    var androidTrack = findBestAndroidCaptionTrack(getCaptionTracksFromPlayerResponse(playerResponse), track);
    var timedTextResult;

    if (!androidTrack) {
      return {
        ok: false,
        reason: "No Android player caption track found",
        source: "android-player"
      };
    }

    if (track && track.isTranslated) {
      androidTrack = Object.assign({}, androidTrack, {
        isTranslated: true,
        label: track.label || "English (translated)",
        kind: "translated",
        languageCode: track.languageCode || "en",
        sourceLanguageCode: androidTrack.languageCode,
        translationLanguageCode: track.translationLanguageCode || "en"
      });
    }

    timedTextResult = await fetchTimedTextTranscript(androidTrack, fetchFn, options);

    if (!timedTextResult.ok) {
      return {
        ok: false,
        reason: timedTextResult.reason,
        source: "android-player"
      };
    }

    return {
      ok: true,
      rows: timedTextResult.rows,
      source: "android-player"
    };
  }

  function getTrackIdentity(track) {
    if (!track) {
      return "";
    }

    return [
      track.baseUrl || "",
      track.languageCode || "",
      track.kind || "",
      track.isTranslated ? "translated" : "direct",
      track.translationLanguageCode || ""
    ].join("|");
  }

  function getFallbackTrackSequence(primaryTrack, tracks) {
    var orderedTracks = [];
    var seen = {};

    function addTrack(track) {
      var key;

      if (!track || !track.baseUrl) {
        return;
      }

      key = getTrackIdentity(track);

      if (seen[key]) {
        return;
      }

      seen[key] = true;
      orderedTracks.push(track);
    }

    addTrack(primaryTrack);

    if (Array.isArray(tracks)) {
      tracks.forEach(addTrack);
    }

    return orderedTracks;
  }

  function hasDirectCaptionTrack(tracks) {
    return tracks.some(function findDirectTrack(track) {
      return !track.isTranslated;
    });
  }

  async function fetchTranscriptRowsWithFallbacks(options) {
    var safeOptions = options || {};
    var videoId = safeOptions.videoId;
    var fetchFn = safeOptions.fetchFn;
    var nativeTranscriptFetcher = safeOptions.nativeTranscriptFetcher;
    var tracks = getFallbackTrackSequence(safeOptions.track, safeOptions.tracks);
    var lastTimedTextReason = "";
    var lastAndroidReason = "";
    var timedTextResult;
    var nativeRows;
    var androidResult;
    var index;

    if (tracks.length === 0) {
      return {
        ok: false,
        reason: "No caption tracks were provided",
        source: "pipeline"
      };
    }

    for (index = 0; index < tracks.length; index += 1) {
      timedTextResult = await fetchTimedTextTranscript(tracks[index], fetchFn, safeOptions);

      if (timedTextResult.ok) {
        return timedTextResult;
      }

      lastTimedTextReason = timedTextResult.reason;
    }

    if (hasDirectCaptionTrack(tracks) && typeof nativeTranscriptFetcher === "function") {
      try {
        nativeRows = await nativeTranscriptFetcher();

        if (Array.isArray(nativeRows) && nativeRows.length > 0) {
          return {
            ok: true,
            rows: nativeRows,
            source: "native-transcript-panel"
          };
        }
      } catch (error) {
        logCaptionDebug(safeOptions, "Native transcript fallback failed: " + getErrorMessage(error));
      }
    }

    for (index = 0; index < tracks.length; index += 1) {
      androidResult = await fetchAndroidPlayerTranscript(videoId, tracks[index], safeOptions.apiKey, fetchFn, safeOptions);

      if (androidResult.ok) {
        return androidResult;
      }

      lastAndroidReason = androidResult.reason;
    }

    return {
      ok: false,
      reason: lastAndroidReason || lastTimedTextReason || "No YouTube transcript is available for this video.",
      source: "pipeline"
    };
  }

  async function detectTranscriptAvailability(options) {
    var safeOptions = options || {};
    var videoId = safeOptions.videoId;
    var documentValue = safeOptions.document || root.document;
    var fetchFn = safeOptions.fetchFn || root.fetch;
    var apiKey;
    var trackSource;
    var foundPlayerResponseWithoutTracks = false;

    if (!videoId) {
      return createFailedAvailabilityResult();
    }

    try {
      apiKey = findInnertubeApiKeyInDocument(documentValue);
      trackSource = getCaptionTracksFromLivePlayerResponse(videoId);

      if (trackSource.ok) {
        trackSource.apiKey = apiKey;
        return createAvailabilityResultFromTrackSource(trackSource);
      }

      foundPlayerResponseWithoutTracks = foundPlayerResponseWithoutTracks || trackSource.foundPlayerResponse;

      trackSource = getCaptionTracksFromScriptTags(videoId, documentValue);

      if (trackSource.ok) {
        if (!trackSource.apiKey) {
          trackSource.apiKey = apiKey;
        }

        return createAvailabilityResultFromTrackSource(trackSource);
      }

      foundPlayerResponseWithoutTracks = foundPlayerResponseWithoutTracks || trackSource.foundPlayerResponse;

      trackSource = await getCaptionTracksFromWatchPageFetch(videoId, fetchFn);

      if (trackSource.ok) {
        return createAvailabilityResultFromTrackSource(trackSource);
      }

      foundPlayerResponseWithoutTracks = foundPlayerResponseWithoutTracks || trackSource.foundPlayerResponse;

      if (foundPlayerResponseWithoutTracks) {
        return createUnavailableAvailabilityResult();
      }

      return createFailedAvailabilityResult();
    } catch (error) {
      return createFailedAvailabilityResult();
    }
  }

  var api = {
    createCheckingAvailabilityResult: createCheckingAvailabilityResult,
    createAvailabilityResultFromPlayerResponse: createAvailabilityResultFromPlayerResponse,
    createFailedAvailabilityResult: createFailedAvailabilityResult,
    createUnavailableAvailabilityResult: createUnavailableAvailabilityResult,
    buildCaptionFetchUrls: buildCaptionFetchUrls,
    detectTranscriptAvailability: detectTranscriptAvailability,
    extractPlayerResponseFromHtml: extractPlayerResponseFromHtml,
    fetchAndroidPlayerTranscript: fetchAndroidPlayerTranscript,
    fetchTimedTextTranscript: fetchTimedTextTranscript,
    fetchTranscriptTrack: fetchTranscriptTrack,
    fetchTranscriptRowsWithFallbacks: fetchTranscriptRowsWithFallbacks,
    getCaptionTracksFromLivePlayerResponse: getCaptionTracksFromLivePlayerResponse,
    getCaptionTracksFromPlayerResponse: getCaptionTracksFromPlayerResponse,
    getCaptionTracksFromScriptTags: getCaptionTracksFromScriptTags,
    getCaptionTracksFromWatchPageFetch: getCaptionTracksFromWatchPageFetch,
    parseNativeTranscriptRowsFromDocument: parseNativeTranscriptRowsFromDocument,
    parseTranscriptResponse: parseTranscriptResponse
  };

  root.YTTranscriptTranscript = api;

  if (typeof module !== "undefined" && module.exports) {
    module.exports = api;
  }
})(typeof globalThis !== "undefined" ? globalThis : window);
